name: doc.htwinkle - deploy

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: 16

      - name: show dir
        run: ls

      - name: npm install vuepress-reco environment
        run: npm install -g @vuepress-reco/theme-cli@1.0.7

      - name: npm install vue environment
        run: npm install -g @vue/cli@5.0.4

      - name: yarn install dependencies
        run: npm install
        
      - name: build package
        run: |
          npm run build
          ls
          
      - name: delete server dir
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          run: |
              echo 'delete old dir'
              rm -rf /home/app/doc.htwinkle/public
              
      - name: show server dir
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          run: |
              echo 'change dir'
              cd /home/app/doc.htwinkle
              ls
              
      - name: upload static to server
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          local: "./public*"
          remote: "/home/app/doc.htwinkle/"
              
          
          
          
          
          
