name: doc.htwinkle - deploy

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: 14

      - name: show dir
        run: ls

      - name: install enviroment
        run: npm install
        
      - name: install webpack
        run: npm install webpack@^4.5.0 -D  
        
      - name: build package
        run: |
          npm run build
          ls
          
          
          
          
